# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: fr
seo_lang: fr_FR
title: Socio Jam
author: Marguerite Pometko
email: marguerite.pometko@gmail.com
description: Bienvenue sur mon blog personnel ! Passionnée par les relations sciences-société (mais pas que), j'organise des débats, j'anime des projets et je rédige des articles sur les enjeux des sciences et techniques. 

baseurl: "" # the subpath of your site, e.g. /blog
# url: https://marguerite-p.github.io # the base hostname & protocol for your site, e.g. http://example.com

icons:
  small: /assets/images/square-sj-48x48.png
  medium: /assets/images/square-sj-96x96.png
  large: /assets/images/square-sj-192x192.png


# for sharing best prectices, see:
# https://developers.facebook.com/docs/sharing/best-practices/
# https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
share_image: /assets/images/square-socio-jam-375x375.png
preview_image: /assets/images/banner-socio-jam-300x200.png
twitter:
  handle: SocioJam
facebook:
  app_id: 2035787453363407
  profile_id: 100004117324768
google:
  analytics: UA-115755576-1
disqus_name: socio-jam

webmaster_verifications:
  google: fRM8uqs3IkUcjrYN47zIezEKi7JQCzXgxirTV4t6G6Y

timezone: Europe/Paris

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Build settings
exclude:
  - package.json
  - package-lock.json
  - gulpfile.js
  - node_modules
  - README.md
  - CNAME
  - assets/sass
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

permalink: /blog/:year/:month/:title.html
collections:
  # posts:
  #   output: true
  #   permalink: /:name
  custom_pages:
    output: true
    permalink: /:name.html
  custom_categories:
    output: true
    permalink: /blog/:name.html

defaults:
  -
    scope:
      path: _custom_pages
      type: custom_pages
    values:
      layout: page
      enabled: true
      top-nav: true
  -
    scope:
      path: _custom_categories
      type: custom_categories
    values:
      layout: category
      nav: blog
  -
    scope:
      path: _posts # an empty string here means all files in the project
    values:
      layout: post
      nav: blog
      comments: true
